from utils.filter.fil_passage_copyright import FilterPassageByCopyright
from utils.filter.fil_passage_dirtywords import FilterPassageByDirtyWords
from utils.filter.fil_passage_length import FilterPassageByLength
from utils.filter.fil_passage_propalphanum import FilterPassageByProportionOfAlphaNumber
from utils.filter.fil_passage_propnonzh import FilterPassageByProportionOfNonChineseChars
from utils.filter.fil_passage_propshortline import FilterPassageByProportionofShortline
from utils.filter.fil_passage_selfdefuncs import FilterPassageBySelfDefinedFunctions